name: Continuous Integration
on:
  push:
    branches: [main]
  workflow_call:

permissions:
  contents: read

jobs:
  build-website:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/aliaumel/transducer-exercices:main
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Builds the static website
        run: make website
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: static-website
          path: ./site
  build-pdfs:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/aliaumel/transducer-exercices:main
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Builds the tar.gz archive
        run: make pdfs.tar.gz
      - name: Builds the zip archive
        run: make pdfs.zip
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: exercises-pdf.tar.gz
          path: pdfs.tar.gz
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: exercises-pdf.zip
          path: pdfs.zip
