# This worflow bulids a Docker image
# containing all the necessary packages
# to build the website and pdf documents
#
# For more information see:
# https://docs.github.com/en/actions/guides/publishing-docker-images
#
# This docker image is used by the other workflows in this repository
# to build the website and pdf archives.
#

name: Build Docker Image
# We only run the build when explicitly asked to
on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMPAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Log in to the Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
