name: Produce Pdf Folder

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build-assets:
    uses: ./.github/workflows/continuous-integration.yml
  build-release:
    name: build-release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Get Artifacts (tar)
        uses: actions/download-artifact@v4
        with:
          name: exercices-pdf.tar.gz
      - name: Get Artifacts (zip)
        uses: actions/download-artifact@v4
        with:
          name: exercices-pdf.zip
      - name: Create the release with artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            exercises-pdf.tar.gz 
            exercises-pdf.zip
          body_path: CHANGELOG.md
