name: release-pdfs

on:
  push:
    tags:
      - '*'
  workflow_dispatch: 

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Nix
        uses: cachix/install-nix-action@v17
      - name: Build pdfs.tar.gz
        run: nix develop --command make pdfs.tar.gz
      - name: Build pdfs.zip
        run: nix develop --command make pdfs.zip
      - name: Create the release with artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            pdfs.tar.gz 
            pdfs.zip
          body_path: CHANGELOG.md
