name: release-pdfs

on:
  push:
    tags:
      - '*'
  workflow_dispatch: 

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    container: danteev/texlive:latest
    steps:
      - name: Setup dev environment (without caching)
        run: |
          apt update
          apt install fonts-dosis python3-venv -y
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: build artifacts
        run: |
          python3 -m venv .venv
          . .venv/bin/activate
          pip3 install panflute
          make pdfs.tar.gz && make pdfs.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            pdfs.tar.gz 
            pdfs.zip
          body_path: CHANGELOG.md
