name: release-pdfs

on:
  push:
    tags:
      - '*'
  workflow_dispatch: 

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Build pdfs.tar.gz
        run: nix-shell --run "make pdfs.tar.gz"
      - name: Build pdfs.zip
        run: nix-shell --run "make pdfs.zip"
      - name: Create the release with artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            pdfs.tar.gz 
            pdfs.zip
          body_path: CHANGELOG.md
